### ISSUE TITLE
Add feature to navigate in the REPL

### ISSUE THREAD

**Issue by eznix86** [zurvan-lab/timetrace#112]
## Describe the problem you'd like to have solved

Unable to navigate on the REPL

### Describe the ideal solution

History: Ability to do UP and DOWN on keyboard to display previous commands or to navigate forward or backward
Navigation during REPL: LEFT OR RIGHT to be able to move left or right of the current command. 
      - Maybe we could add ctrl/option also so we can jump word backward and forward. (ex. Mac OS  = Option+LEFT to jump a word backward)

### Alternatives and current work-around

None

### Additional context

When trying to replay last command noticed, it doesn't show the previous command but just display:

```shell
>> PING
PONG
>> ^[[A
INVALID
>> ^[[A    
INVALID
```

Navigation issue:

```
>> SET website:likes^[b^[b^[[D^[[D
```
Above I was trying to change SET TO GET. I cannot press left button.

**Comment by kehiy** [comment]
@eznix86 Hi, thank you for your suggestion.
