### ISSUE TITLE
Dot commands

### ISSUE THREAD

**Issue by eznix86** [zurvan-lab/timetrace#114]
## Describe the problem you'd like to have solved

it would be nice if we had dot commands similar to SQLite. The purpose of dot commands is to run persistent or session based configuration.

### Describe the ideal solution

It can reflect what we have in the `config.yml` but it can be run override at runtime or be persistent.

once nice command would be `.config verbose=true`  or `.config output.time=true` which prints useful information alongside the REPL output.

```
>> .config verbose=true
>> PING
PONG
elapse: 0.2ms connection: 0.2ms replied: 0.1ms
```
We can have .whatever 

### Alternatives and current work-around

None

### Additional context

```
>> .config verbose=true
>> .config verbose
1
>> .config verbose=false
>> .config verbose
0
```
For example can tell me that verbose can be toggle and viewed.

```
>> .config verbose=true
>> PING
PONG
elapse: 0.2ms connection: 0.2ms replied: 0.1ms
```

Example this can show how much the server replied, and show us if it is the server or the client is problem.

```
>> .log
log.ttrace
>> .log log2.ttrace
>> .log
log2.ttrace
```

Another example instead of prefixing everything of .config. Here I have override the config but at session level.

```
>> .max_log_size 1000
You cannot change this configuration at run time. Change it your configuration file instead
>> .max_log_size
10
```
Here it denied the change to a config

```
>> .mode
line
>> GET myset mysset
 hello-123456789  hello-1212  hello-123456789  hello-123456789  hello-123456789 
>> .mode row
>> GET myset mysset
 hello-123456789     
 hello-1212
 hello-123456789
 hello-123456789
 hello-123456789
>> .mode ascii
>> GET myset mysset

+-----------------+
| hello-123456789 |
+-----------------+
| hello-1212      |
+-----------------+
| hello-123456789 |
+-----------------+
| hello-123456789 |
+-----------------+
| hello-123456789 |
+-----------------+
>> .mode box
>> GET myset mysset

┌─────────────────┐
│hello-123456789  │
├─────────────────┤
│hello-1212       │
├─────────────────┤
│hello-123456789  │
├─────────────────┤
│hello-123456789  │
├─────────────────┤
│hello-123456789  │
└─────────────────┘
```

**Comment by kehiy** [comment]
@eznix86 Should we support this runtime config change also for clients connected to TCP server and talking with TQL, or just in REPL?

I mean they they are commands for TQL and core, or just reply feature?

**Comment by eznix86** [comment]
why not both !

**Comment by kehiy** [comment]
@eznix86 The issue is our current command model is a little complex to support it I think.

Only the change will be applied to the reply if we change the verbose mode. not other type of clients.

Do you have any idea for implementation? 

I think we can add a command and simply modify the config struct on database. what do you think?
