### ISSUE TITLE
Installation via homebrew

### ISSUE THREAD

**Issue by eznix86** [zurvan-lab/timetrace#120]
## Describe the problem you'd like to have solved

Right now, we have go to go release to get a version of timetrace

### Describe the ideal solution

One simplest form of package manager is homebrew for MacOS

### Alternatives and current work-around

Using releases

### Additional context

None

**Comment by eznix86** [comment]
https://github.com/eznix86/homebrew-timetrace/

**Comment by eznix86** [comment]
I think it is possible, but snap requires an account at ubuntu snap store to be able to publish, never tried to publish on pacman but i can try.

@kehiy https://github.com/eznix86/homebrew-timetrace updated with documentation. Make `zurvan-lab` can fork the repository  and sync the fork ?

**Comment by kehiy** [comment]
@eznix86 You can make a PR and add your repo as a way to download the ttrace.

Our repo readme needs enhancement.


Also, in next release I think we have to support:

1. snap
2. pacman
3. homebrew
4. docker
5. apt
6. bash installer script (best?)

Add if I missed anything.

**Comment by eznix86** [comment]
i think, to start, maybe, we have a bash script you can just run and it build it from source for every systems: mac/linux

**Comment by kehiy** [comment]
Yes, I'll write the script soon. please make PR and add your repo as installation way as well.
