### ISSUE TITLE
Remove StringToBytes and BytesToString functions from random utils

### ISSUE THREAD

**Issue by kehiy** [zurvan-lab/TimeTrace#44]

**Comment by kehiy** [comment]
@Kamandlou can you work on this one?

**Comment by ErfanTech** [comment]
Hi there,

I'd like to take on this issue and remove the `StringToBytes` and `BytesToString` functions from the random utils. I'll get started on it right away. Please assign this issue to me if needed.

Thanks!

**Comment by kehiy** [comment]
@ErfanTech it's assigned ti you now(:
