### ISSUE TITLE
Complete auth system

### ISSUE THREAD

**Issue by kehiy** [zurvan-lab/TimeTrace#48]
Complete auth system by what we discussed in:
- #33

**Comment by MostPow3rful** [comment]
when we are going to implement auth system ?

**Comment by kehiy** [comment]
@MostPow3rful from now to the end of this week is a good time.
what's your opinion?

**Comment by MostPow3rful** [comment]
from saturday until the end of next week with plan and discussion with other developers

**Comment by kehiy** [comment]
@MostPow3rful that's okay, send your preferred time in discord server, we can make an event for it.

**Comment by kehiy** [comment]
- #49 
The config is done now!
I will send some tip for finishing auth system soon.

**Comment by kehiy** [comment]
@MostPow3rful 
We need a function that gets 2 string parameters, user and password.
And it should return a value of true or false!

it can be a method of database or config or just a separate function.
also, it can be implemented in the database.go or a file with the name: auth.go or ...

the name and the way of implementation is up to you.
