### ISSUE TITLE
file extention

### ISSUE THREAD

**Issue by kehiy** [zurvan-lab/TimeTrace#62]
using the `.ttrace` file extension for logs and snapshots in the whole of the project.

example:
`log.ttrace` instead of `ttrace.log` in the config log path.

> and considering using it when the snapshot is implemented.

**Comment by bansaltushar014** [comment]
Could you assign this task to me ? I would like to work on it.

**Comment by kehiy** [comment]
@bansaltushar014 yeap, it's assigned to you now.
you can just change the log file name in yaml file of config and add a small comment and remind it's the time trace file extentions.

**Comment by bansaltushar014** [comment]
@kehiy Please review it.
