### ISSUE TITLE
Fixing large response writing on TCP connection

### ISSUE THREAD

**Issue by kehiy** [zurvan-lab/timetrace#90]
When we have a large response for a `GET` query, the server can't write the whole response on user's TCP connection and it will be imperfect data.

We need to enhance this line and send data in another way. (we can stream the result(?))
https://github.com/zurvan-lab/TimeTrace/blob/fdfae8ea172049890035294c6b775756f154cdb4/core/server/server.go#L133

**Comment by adarshjhaa100** [comment]
Yeah streaming would help. Set an upper limit (BUFFER_SIZE) on the buffer size and you have to stream it one at a time. Connection will have to remain open till then.

**Comment by kehiy** [comment]
@adarshjhaa100 Hi, thank you for this information! We are trying to fix that ASAP. If you are interested to help us please tell us.❤️

**Comment by adarshjhaa100** [comment]
Sure, im interested. I guess we can loop over the payload with a fixed buffer sized and stream those chunks. Also, the code on the client side might need to be changed to combine back those chunks.

If possible, I'd like to know the following:
Do we keep the BUFFER_SIZE fixed or configurable.

Are there some sort of tests and benchmarks used for this particular piece of code.

**Comment by kehiy** [comment]
currently, there is no test, it's a work in progress.
- #85

But you can try your idea on the current code, also I can help you with running and testing it in development time.

I have this gist also which is for streaming large files (data) over a TCP connection. what do you think? can we follow the same approach?
https://gist.github.com/kehiy/4bff455048a8bedf4f9374b8899b2f43

**Comment by adarshjhaa100** [comment]
Oh, this is from the client's perspective, it will work for us.

Let me play with this for a couple of days and I'll reply with a PR soon.

**Comment by kehiy** [comment]
@adarshjhaa100 okay, I'm here if you have any questions about anything in time-trace.

**Comment by 0x9n0p** [comment]
It seems that we should create a simple protocol over TCP.

**Comment by kehiy** [comment]
@0x9n0p I agree, do you have any idea about the protocol itself, or implementing it?
I belive we can enhance results by defining a protocol also.

**Comment by 0x9n0p** [comment]
A protocol that has a content-length on headers and may have other flags in the future.
I have the same issue on [PlutoEngine](https://github.com/0x9n0p/pluto), so I can actively contribute to this protocol.

**Comment by kehiy** [comment]
yes, I agree. we can also try to define a better way to send normal response when we have a protocol. but it need to be documented also. if you can help on this, please ping us on our discord: https://discord.gg/NU5Y2hrd.

**Comment by adarshjhaa100** [comment]
Hello, @kehiy, apologies for the delay. Got busy with Christmas break. 

How do I replicate this bug? I've made some modifications to the server.go and meanwhile testing stuff through REPL, but it's taking time to insert a lot of data.

But, is there any other way to execute the TQL commands quickly with a huge chunks of data? Should I just temporarily modify the [TQL/execute.go](https://github.com/zurvan-lab/TimeTrace/blob/3ca95221fa226204a144d793333b721a732cd876/core/TQL/execute/execute.go#L26-L32) file.

**Comment by kehiy** [comment]
We will work on it on:

- #124
